# Generated by Django 2.2.16 on 2022-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220304_1854'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_sub',
        ),
    ]
